---
- name: Setup WordPress server
  hosts: vm
  become: yes
  become_method: sudo
  become_user: root
  vars:
    ansible_become_password: "Test123!"
    mysql_root_password: "test"
    

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install necessary packages
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - apache2
        - mysql-server
        - php
        - libapache2-mod-php
        - php-mysql

    - name: Install Python and MySQL dependencies
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - python3
        - python3-pip
        - python3-dev
        - libmysqlclient-dev
        - pkg-config

    - name: Install mysqlclient and PyMySQL Python packages
      pip:
        name:
          - mysqlclient
          - PyMySQL
        state: present

    - name: Download WordPress
      get_url:
        url: https://wordpress.org/latest.tar.gz
        dest: /tmp/wordpress.tar.gz

    - name: Extract WordPress
      unarchive:
        src: /tmp/wordpress.tar.gz
        dest: /var/www/html/
        remote_src: yes

    - name: Set permissions
      file:
        path: /var/www/html/wordpress
        owner: www-data
        group: www-data
        state: directory
        recurse: yes

    - name: Create MySQL database
      mysql_db:
        name: wordpress
        state: present

    - name: Create MySQL user
      mysql_user:
        name: wordpress
        password: wordpress
        priv: 'wordpress.*:ALL'
        state: present
        login_user: "{{ mysql_admin_user }}"
        login_password: "{{ mysql_admin_password }}"

